### ISSUE TITLE
Adapt ultrasonic and light pollers to make use of the SensorData class.

### ISSUE THREAD

**Issue by L3gume** [MrL3gume/DPMProject#1]
It is important to keep in mind that the ultrasonic sensor will be used for:

* Ultrasonic localization
* Obstacle avoidance
* Searching for the "flag"

and that the light sensors (3 of them) will be used for:

* (two on the sides) Light localization and angle correction during navigation
* (one of both of the sides) detecting whether or not the robot is grounded (values goes below 0.1 when on zipline)
* (one in the middle) colour identification

**Comment by pwnalone** [comment]
That's what the SensorData class is for - to provide a single location to receive sensor data for whichever classes that need it. I was thinking that the Navigator class could handle both navigation and obstacle avoidance (since it would probably be simpler that way, i.e. we could just implement a state machine where it could be NAVIGATING, AVOIDING_OBSTACLE, etc.).

As for the two extra light sensors, I will add support for them in the SensorData class.

**Comment by L3gume** [comment]
The navigator does handle both navigation and obstacle avoidance.

The task basically means: "write the poller classes" hehe.

EDIT: read through your commit too fast and didn't realize it was already done haha! closing the issue now.
